---

- name: install sasl2-bin
  ansible.builtin.apt:
    name: ['sasl2-bin', 'libsasl2-modules']
    state: present

- name: create sasl dir
  ansible.builtin.file:
    path: /etc/postfix/sasl
    state: directory
    mode: 0755
    owner: 'root'
    group: 'root'

- name: configure smtpd
  ansible.builtin.copy:
    src: smtpd.conf
    dest: /etc/postfix/sasl/smtpd.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: service saslauthd restart

- name: configure saslauthd
  ansible.builtin.template:
    src: saslauthd.default.j2
    dest: /etc/default/saslauthd
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: service saslauthd restart

- name: ensure saslauthd enabled
  ansible.builtin.service:
    name: saslauthd
    enabled: true
    state: started
